import 'package:flutter/material.dart';

const Color backgroundColor = Color(0xffE4E4E4);
const Color darkBlueColor = Color(0xff0A0F22);
const Color textFormFiledColor = Color(0xffF7F7F7);
const Color hintTextColor = Color(0xff8C8C8C);
const Color labelTextColor = Color(0xff424242);
const Color innerContainerColor = Color(0xffCFCFCF);
const Color smallContainerColor = Color(0xffD9D9D9);
const Color outputContainerColor = Color(0xffE5E5E5);
const Color outlineButtonTextColor = Color(0xff5D5D5D);
const Color greenTextOnButtonColor = Color(0xffA9FF80);
const Color monitorBgColor = Color(0xff0A0F22);
const Color containerBorderColor = Color(0xff0E6ABF);
const Color drugItemConColor = Color(0xffC4C4C4);
Color lightDigitalNumColor = const Color(0xffAFAFAF).withOpacity(0.10000000);
Color dialogBarrierColor = const Color(0xffA5A4A4).withOpacity(0.5);
Color warningDialogBarrierColor = const Color(0xff04060E).withOpacity(0.8);
List<Color> gradiantGreenColor = const [Color(0xFF6ED93B), Color(0xFF144807)];
List<Color> gradiantRedColor = const [Color(0xFFD93B3B), Color(0xFF480707)];
